version: '3'

networks:
  public:
    driver: bridge
  rabbit-network:

volumes:
#  rabbitmq_data:
  mysql_data:


services:
#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq
#    networks:
#      - public
#    volumes:
#      - rabbitmq_data:/bitnami
#    ports:
#      - 15672:15672 # maybe this can be deleted
#    environment:
#      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
#      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
#    restart: unless-stopped
    
  mysql:
     image: mysql:8
     networks:
       - public
     container_name: mysql
     command: --init-file /data/application/init.sql
     volumes:
       - mysql_data:/var/lib/mysql
       - ./init.sql:/data/application/init.sql
     restart: always
     env_file: .env
     environment:
       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT}
     ports:
       - 3306:3306


  authentication:
    build: .
    container_name: authentication
    networks:
      - public
      - rabbit-network
    depends_on:
      #- rabbitmq
      - mysql
    ports:
      - 8080:80
      - 3000:3000
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
    restart: unless-stopped

#  gateway:
#    build: ./tempGateway
#    container_name: gateway
#    networks:
#      - public
#    depends_on:
#      - rabbitmq
#      - mysql
#      - authentication
#    ports:
#      - 8081:81
#      - 3001:3001
#    env_file: .env
#    environment:
#      - AMQP_USER=${RABBITMQ_DEFAULT_USER}
#      - AMQP_PASS=${RABBITMQ_DEFAULT_PASS}
#      - AMQP_URI=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
#    restart: unless-stopped
